services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: desafio-votacao
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: