spring:
  application:
    name: desafio-votacao
  datasource:
    url: jdbc:postgresql://localhost:5432/desafio-votacao
    username: usuario
    password: senha
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always